<?php

use App\Http\Controllers\adminside\AdminController;
use App\Http\Controllers\employeeside\employeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});
// ====================================================== open routes =========================================================
Route::get('/', function () {
    $selectCompany = DB::table('companies')->get();
    return view('adminside.Authentication.login-form.login', compact('selectCompany'));
})->name('loginForm');
Route::post('/LoginOperation', [AdminController::class, 'loginOperation'])->name('loginOperation');
// ====================================================== ! open routes =======================================================
// ====================================================== admin routes ========================================================
Route::group(['middleware' => ['admin']], function () {
    Route::get('/adminSideDashboard', [AdminController::class, 'adminDashboardPage'])->name('adminDashboardPage');
    // logout operation
    Route::any('LogoutOperation', [AdminController::class, 'logoutOperations'])->name('logoutOperations');
    Route::get('CompanyListPage', [AdminController::class, 'companyNameList'])->name('companyNameList');
    // company creating page
    Route::get('/CompanyCreatingForm', [AdminController::class, 'pageCreatingCompany'])->name('pageCreatingCompany');
    Route::post('/CreatingCompanyOperation', [AdminController::class, 'createComponyOperation'])->name('createComponyOperation');
    Route::any('/CompanyRemovedOperation/{id}', [AdminController::class, 'removedCompanyInformation'])->name('removedCompanyInformation');
    Route::get('/searchCompanyOperation', [AdminController::class, 'searchCompany'])->name('searchCompany');
    Route::get('/CompanyEditPage/{id}', [AdminController::class, 'editPageCompany'])->name('editPageCompany');
    Route::get('/CompanyDetailsPage/{id}', [AdminController::class, 'detailsPageCompany'])->name('detailsPageCompany');
    Route::any('/updateOperationCompany/{id}', [AdminController::class, 'updateCompanyOperation'])->name('updateCompanyOperation');
    Route::get('/clientListPage', [AdminController::class, 'clientNameList'])->name('clientNameList');
    Route::get('/ClientCreatingForm', [AdminController::class, 'pageCreatingClient'])->name('pageCreatingClient');
    Route::post('/clientCreationOperation', [AdminController::class, 'clientCreationOperation'])->name('clientCreationOperation');
    Route::post('/searchClientOperation', [AdminController::class, 'searchClient'])->name('searchClient');
    Route::any('/ClientRemovedOperation/{id}', [AdminController::class, 'removeClientInformationOperation'])->name('removeClientInformationOperation');
    Route::get('/ClientEditPage/{id}', [AdminController::class, 'editPageClient'])->name('editPageClient');
    Route::any('/updateOperationClient/{id}', [AdminController::class, 'updateClientOperation'])->name('updateClientOperation');
    Route::get('/ClientDeatilsPage/{id}', [AdminController::class, 'detailClientPage'])->name('detailClientPage');
    Route::get('/employeeListPage', [AdminController::class, 'employeeNameList'])->name('employeeNameList');
    Route::get('/createEmployeePage', [AdminController::class, 'pageCreatingEmployee'])->name('pageCreatingEmployee');
    Route::post('/createEmployeeOperation', [AdminController::class, 'createOperationEmployee'])->name('createOperationEmployee');
    Route::get('/searchEmployeeOperations', [AdminController::class, 'searchEmployee'])->name('searchEmployee');
    Route::any('/removeEmployeeOperation/{id}', [AdminController::class, 'removeOperationEmployee'])->name('removeOperationEmployee');
    Route::get('/EditEmployeePages/{id}', [AdminController::class, 'editEmployeePage'])->name('editEmployeePage');
    Route::any('/updateEmployeeOperation/{id}', [AdminController::class, 'updateEmployeeOperation'])->name('updateEmployeeOperation');
    Route::get('/detailEmployeePage/{id}', [AdminController::class, 'detailEmployeePage'])->name('detailEmployeePage');
    Route::get('/incomingInspectionReportWithoutTjfPage', [AdminController::class, 'withoutTjfInspectionIncomingListPage'])->name('withoutTjfInspectionIncomingListPage');
    Route::get('/incomingCreatingInspectionReportWithoutTjfPage', [AdminController::class, 'withoutTjfInspectionIncomingCreatingPage'])->name('withoutTjfInspectionIncomingCreatingPage');
    Route::post('/withoutTjfInspectionIncomingCreateOperation', [AdminController::class, 'withoutTjfInspectionIncomingCreateOperation'])->name('withoutTjfInspectionIncomingCreateOperation');
    Route::post('searchIncomingGastroAndColonoScopeReport', [AdminController::class, 'searchIncomingGastroAndColonoScopeReport'])->name('searchIncomingGastroAndColonoScopeReport');
    Route::get('/detailsPageIncomingGastroAndColonoScope/{id}', [AdminController::class, 'detailsPageIncomingGastroAndColonoScope'])->name('detailsPageIncomingGastroAndColonoScope');
    Route::get('/editPageIncomingGastroAndColonoScope/{id}', [AdminController::class, 'withoutTjfInspectionIncomingEditPage'])->name('withoutTjfInspectionIncomingEditPage');
    Route::any('/updateWithoutTjfInspectionIncomingReport/{id}', [AdminController::class, 'updateWithoutTjfInspectionIncomingReport'])->name('updateWithoutTjfInspectionIncomingReport');
    Route::any('/removeWithoutTjfInspectionIncomingReport/{id}', [AdminController::class, 'removeWithoutTjfInspectionIncomingReport'])->name('removeWithoutTjfInspectionIncomingReport');
    Route::get('/outgoingInspectionReportWithoutTjfPage', [AdminController::class, 'withoutTjfInspectionOutgoingListPage'])->name('withoutTjfInspectionOutgoingListPage');
    Route::get('/outgoingCreatingInspectionReportWithoutTjfPage/{id}', [AdminController::class, 'withoutTjfInspectionOutgoingCreatingPage'])->name('withoutTjfInspectionOutgoingCreatingPage');
    Route::any('/withoutTjfInspectionOutgoingCreatingOperation', [AdminController::class, 'withoutTjfInspectionOutgoingCreatingOperation'])->name('withoutTjfInspectionOutgoingCreatingOperation');
    Route::get('searchOutgoingGastroAndColonoScopeReport', [AdminController::class, 'searchOutgoingGastroAndColonoScopeReport'])->name('searchOutgoingGastroAndColonoScopeReport');
    Route::get('/detailsPageOutgoingGastroAndColonoScope/{id}', [AdminController::class, 'detailsPageOutgoingGastroAndColonoScope'])->name('detailsPageOutgoingGastroAndColonoScope');
    Route::get('/editPageOutgoingGastroAndColonoScope/{id}', [AdminController::class, 'withoutTjfInspectionOutgoingEditPage'])->name('withoutTjfInspectionOutgoingEditPage');
    Route::any('/updateWithoutTjfInspectionOutgoingReport/{id}', [AdminController::class, 'updateWithoutTjfInspectionOutgoingReport'])->name('updateWithoutTjfInspectionOutgoingReport');
    Route::any('/removeWithoutTjfInspectionOutgoingReport/{id}', [AdminController::class, 'removeWithoutTjfInspectionOutgoingReport'])->name('removeWithoutTjfInspectionOutgoingReport');
    Route::get('/incomingInspectionReportTjfPage', [AdminController::class, 'TjfInspectionIncomingListPage'])->name('TjfInspectionIncomingListPage');
    Route::get('/incomingCreatingInspectionReportTjfPage', [AdminController::class, 'TjfInspectionIncomingCreatingPage'])->name('TjfInspectionIncomingCreatingPage');
    Route::post('/tjfInspectionIncomingCreateOperation', [AdminController::class, 'TjfInspectionIncomingCreateOperation'])->name('TjfInspectionIncomingCreateOperation');
    Route::any('/updateTjfInspectionIncomingReport/{id}', [AdminController::class, 'TjfInspectionIncomingReport'])->name('TjfInspectionIncomingReport');
    Route::any('/TjfInspectionOutgoingCreatingOperation', [AdminController::class, 'TjfInspectionOutgoingCreatingOperation'])->name('TjfInspectionOutgoingCreatingOperation');
    Route::get('/creatingPagesDailyRecords/{id}', [AdminController::class, 'createIncomingAndOutGoingDailyRecordPages'])->name('createIncomingAndOutGoingDailyRecordPages');
    Route::post('/creatingOperationDailyIncomingRecord', [AdminController::class, 'createOperationIncomingAndOutgoingDailyRecord'])->name('createOperationIncomingAndOutgoingDailyRecord');
    Route::get('incomingAndOutgoingDailyRecordList', [AdminController::class, 'incomingAndOutGoingDailyRecordList'])->name('incomingAndOutGoingDailyRecordList');
    Route::get('/editPagesDailyRecords/{id}', [AdminController::class, 'incomingAndOutGoingDailyRecordEditPage'])->name('incomingAndOutGoingDailyRecordEditPage');
    Route::any('/editOperationDailyIncomingRecord/{id}', [AdminController::class, 'editOperationIncomingAndOutgoingDailyRecord'])->name('editOperationIncomingAndOutgoingDailyRecord');
    Route::post('/searchOperationData', [AdminController::class, 'searchDataaa'])->name('searchDataaa');
    route::any('/removeScopeDailyInomingAndOutgoingRecordOperation/{id}', [AdminController::class, 'removeScopeDailyInomingAndOutgoingRecord'])->name('removeScopeDailyInomingAndOutgoingRecord');
    Route::get('/createRepairingQuotationPage', [AdminController::class, 'createRepairingQuotationPage'])->name('createRepairingQuotationPage');
    Route::post('/createQuotationRepairingOperation', [AdminController::class, 'createQuotationRepairingOperation'])->name('createQuotationRepairingOperation');
    Route::get('/createDisposibleQuotationPage', [AdminController::class, 'createDisposibleQuotationPage'])->name('createDisposibleQuotationPage');
    Route::post('/createQuotationDisposibleOperation', [AdminController::class, 'createQuotationDisposibleOperation'])->name('createQuotationDisposibleOperation');
    Route::get('/quotationListPage', [AdminController::class, 'quotationListPage'])->name('quotationListPage');
    Route::get('/quotationWithoutLogoListPage', [AdminController::class, 'quotationListWithOutLogoPage'])->name('quotationListWithOutLogoPage');
    Route::post('/searchOperationQuotation', [AdminController::class, 'searchQuotations'])->name('searchQuotations');
    Route::post('/searchQuotationsWithOut', [AdminController::class, 'searchQuotationsWithOut'])->name('searchQuotationsWithOut');
    Route::get('/editPageQuotation/{id}', [AdminController::class, 'editPageQuotation'])->name('editPageQuotation');
    Route::any('/loginScreenQuotation/{id}', [AdminController::class, 'lockscreenQuotation'])->name('lockscreenQuotation');
    Route::any('/updateRepairingQuotationOperation/{id}', [AdminController::class, 'editQuotationRepairingOperation'])->name('editQuotationRepairingOperation');
    Route::any('/updateDisposibleQuotationOperation/{id}', [AdminController::class, 'editQuotationDisposibleOperation'])->name('editQuotationDisposibleOperation');
    Route::get('/detailQuotationPage/{id}', [AdminController::class, 'detailQuotationPage'])->name('detailQuotationPage');
    Route::get('/detailQuotationWithoutLogoPage/{id}', [AdminController::class, 'detailWithOutLogoQuotationPage'])->name('detailWithOutLogoQuotationPage');
    Route::any('/removedOperationQuotation/{id}', [AdminController::class, 'removeQuotationPage'])->name('removeQuotationPage');
    Route::get('/createInvoicePage/{id}', [AdminController::class, 'createInvoicePage'])->name('createInvoicePage');
    Route::post('/createInvoiceDisposibleOperation', [AdminController::class, 'createInvoiceDisposibleOperation'])->name('createInvoiceDisposibleOperation');
    Route::post('/createInvoiceRepairingOperation', [AdminController::class, 'createInvoiceRepairingOperation'])->name('createInvoiceRepairingOperation');
    Route::post('/createInvoiceDisposibleOperations', [AdminController::class, 'createInvoiceDisposibleOperations'])->name('createInvoiceDisposibleOperations');
    Route::post('/createInvoiceRepairingOperations', [AdminController::class, 'createInvoiceRepairingOperations'])->name('createInvoiceRepairingOperations');
    Route::get('/invoiceListPage', [AdminController::class, 'invoiceListPage'])->name('invoiceListPage');
    Route::get('/invoiceWithoutLogoListPage', [AdminController::class, 'invoiceListWithOutLogoPage'])->name('invoiceListWithOutLogoPage');
    Route::post('/searchOperationInvoice', [AdminController::class, 'searchInvoices'])->name('searchInvoices');
    Route::post('/searchOperationInvoices', [AdminController::class, 'searchInvoicess'])->name('searchInvoicess');
    Route::get('/editPageInvoice/{id}', [AdminController::class, 'editPageInvoice'])->name('editPageInvoice');
    Route::any('/loginScreenInvoice/{id}', [AdminController::class, 'lockscreenInvoice'])->name('lockscreenInvoice');
    Route::any('/updateRepairingInvoiceOperation/{id}', [AdminController::class, 'editInvoiceDisposibleOperation'])->name('editInvoiceDisposibleOperation');
    Route::any('/updateDisposibleInvoiceOperation/{id}', [AdminController::class, 'editInvoiceRepairingOperation'])->name('editInvoiceRepairingOperation');
    Route::any('/removedOperationInvoice/{id}', [AdminController::class, 'removeInvoicePage'])->name('removeInvoicePage');
    Route::get('/detailInvoicePage/{id}', [AdminController::class, 'detailInvoicePage'])->name('detailInvoicePage');
    Route::get('/detailWithoutInvoicePage/{id}', [AdminController::class, 'detailWithOutLogoInvoicePage'])->name('detailWithOutLogoInvoicePage');
    Route::get('/createRepairingInvoicePage', [AdminController::class, 'createRepairingInvoicePage'])->name('createRepairingInvoicePage');
    Route::get('/createDisposibleInvoicePage', [AdminController::class, 'createDisposibleInvoicePage'])->name('createDisposibleInvoicePage');
    Route::get('/createDeliveryChallanPage/{id}', [AdminController::class, 'createDeliveryChallanPage'])->name('createDeliveryChallanPage');
    Route::post('/createOperationDeliveryChallan', [AdminController::class, 'createDeliveryChallanOperation'])->name('createDeliveryChallanOperation');
    Route::post('/createOperationDeliveryChallans', [AdminController::class, 'createDeliveryChallanOperations'])->name('createDeliveryChallanOperations');
    Route::get('/deliveryChallanListPage', [AdminController::class, 'deliveryChallanListPage'])->name('deliveryChallanListPage');
    Route::post('/searchDeliveryChallan', [AdminController::class, 'searchDeliveryChallan'])->name('searchDeliveryChallan');
    Route::get('/editPageDeliveryChallan/{id}', [AdminController::class, 'editPageDeliveryChallan'])->name('editPageDeliveryChallan');
    Route::any('/loginScreenDeliveryChallan/{id}', [AdminController::class, 'lockscreenDeliveryChallan'])->name('lockscreenDeliveryChallan');
    // Route::any('/updateDeliveryChallanOperation/{id}',[AdminController::class,'editDeliveryChallanOperation'])->name('');
    Route::any('/editDeliveryChallanOperation/{id}', [AdminController::class, 'editDeliveryChallanOperation'])->name('editDeliveryChallanOperation');
    Route::get('/detailDeleiveryChallanPage/{id}', [AdminController::class, 'detailDeleiveryChallanPage'])->name('detailDeleiveryChallanPage');
    Route::any('/removeOperationDeliveryChallan/{id}', [AdminController::class, 'removeOperationDeliveryChallan'])->name('removeOperationDeliveryChallan');
    Route::get('/createServiceReportPage', [AdminController::class, 'createServiceReportPage'])->name('createServiceReportPage');
    Route::post('/createServiceReportOperation', [AdminController::class, 'createServiceReportOperation'])->name('createServiceReportOperation');
    Route::get('/serviceReportListPage', [AdminController::class, 'serviceReportListPage'])->name('serviceReportListPage');
    Route::post('/searchServiceReport', [AdminController::class, 'searchServiceReport'])->name('searchServiceReport');
    Route::get('/detailServiceReportPage/{id}', [AdminController::class, 'detailServiceReportPage'])->name('detailServiceReportPage');
    Route::any('/removeServiceReport/{id}', [AdminController::class, 'removeServiceReport'])->name('removeServiceReport');
    Route::get('/createRepairingDataSS', [AdminController::class, 'createRepairingDataSS'])->name('createRepairingDataSS');
    Route::post('/createQuotationRepairing_Operations', [AdminController::class, 'createQuotationRepairing_Operations'])->name('createQuotationRepairing_Operations');
    Route::get('/createRepairingDataSSInvoice', [AdminController::class, 'createRepairingDataSSInvoice'])->name('createRepairingDataSSInvoice');
    Route::post('/createInvoiceRepairing_Operations', [AdminController::class, 'createInvoiceRepairing_Operations'])->name('createInvoiceRepairing_Operations');
    Route::post('/createInvoiceRepairing_Operation', [AdminController::class, 'createInvoiceRepairing_Operation'])->name('createInvoiceRepairing_Operation');
    Route::any('/updateInvoiceRepairing_Operation/{id}', [AdminController::class, 'updateInvoiceRepairing_Operation'])->name('updateInvoiceRepairing_Operation');
    Route::any('/updateQuotationRepairing_Operation/{id}', [AdminController::class, 'updateQuotationRepairing_Operations'])->name('updateQuotationRepairing_Operations');
    Route::get('/createIncomingAndOutgoingDisposibleDailyRecord', [AdminController::class, 'createIncomingAndOutgoingDisposibleDailyRecord'])->name('createIncomingAndOutgoingDisposibleDailyRecord');
    Route::post('/createOperationIncomingAndOutgoingDisposibleDailyRecord', [AdminController::class, 'createOperationIncomingAndOutgoingDisposibleDailyRecord'])->name('createOperationIncomingAndOutgoingDisposibleDailyRecord');
    Route::get('/createIncomingAndOutgoingDataDailyRecord', [AdminController::class, 'createIncomingAndOutgoingDataDailyRecord'])->name('createIncomingAndOutgoingDataDailyRecord');
    Route::post('/createOperationIncomingAndOutgoingDataDailyRecord', [AdminController::class, 'createOperationIncomingAndOutgoingDataDailyRecord'])->name('createOperationIncomingAndOutgoingDataDailyRecord');
    Route::get('/IncomingAndOutgoingDataDailyRecordList', [AdminController::class, 'IncomingAndOutgoingDataDailyRecordList'])->name('IncomingAndOutgoingDataDailyRecordList');
    Route::post('/searchOperationIncomingAndOutgoingDataDailyRecord', [AdminController::class, 'searchOperationIncomingAndOutgoingDataDailyRecord'])->name('searchOperationIncomingAndOutgoingDataDailyRecord');
    Route::get('/editIncomingAndOutgoingDataDailyRecordPage/{id}', [AdminController::class, 'editIncomingAndOutgoingDataDailyRecordPage'])->name('editIncomingAndOutgoingDataDailyRecordPage');
    Route::any('/updateOperationIncomingAndOutgoingDisposibleDailyRecord/{id}', [AdminController::class, 'updateOperationIncomingAndOutgoingDisposibleDailyRecord'])->name('updateOperationIncomingAndOutgoingDisposibleDailyRecord');
    Route::any('/updateOperationIncomingAndOutgoingDataDailyRecord/{id}', [AdminController::class, 'updateOperationIncomingAndOutgoingDataDailyRecord'])->name('updateOperationIncomingAndOutgoingDataDailyRecord');
    Route::get('/detailIncomingAndOutgoingDataDailyRecordPage/{id}', [AdminController::class, 'detailIncomingAndOutgoingDataDailyRecordPage'])->name('detailIncomingAndOutgoingDataDailyRecordPage');
    Route::any('/removeOperationIncomingAndOutgoingDataDailyRecord/{id}', [AdminController::class, 'removeOperationIncomingAndOutgoingDataDailyRecord'])->name('removeOperationIncomingAndOutgoingDataDailyRecord');
    Route::get('/getStockData', [AdminController::class, 'getStockData'])->name('getStockData');
    Route::get('/createClientAccountHistoryPage/{id}', [AdminController::class, 'createClientAccountHistoryPage'])->name('createClientAccountHistoryPage');
    Route::post('/createAccountHistoryRepairing_Operation', [AdminController::class, 'createAccountHistoryRepairing_Operation'])->name('createAccountHistoryRepairing_Operation');
    Route::post('/createAccountHistorySystemOperation', [AdminController::class, 'createAccountHistorySystemOperation'])->name('createAccountHistorySystemOperation');
    Route::post('/createAccountHistoryDisposibleOperations', [AdminController::class, 'createAccountHistoryDisposibleOperations'])->name('createAccountHistoryDisposibleOperations');
    Route::get('/viewClientAccountDetailsPage/{id}', [AdminController::class, 'viewClientAccountDetailsPage'])->name('viewClientAccountDetailsPage');
    Route::get('/partListPage', [AdminController::class, 'partListPage'])->name('partListPage');
    Route::get('/disposibleItemsListPage', [AdminController::class, 'disposibleItemsListPage'])->name('disposibleItemsListPage');
    Route::get('/createStockScopesPartsPage', [AdminController::class, 'createStockScopesPartsPage'])->name('createStockScopesPartsPage');
    Route::post('/createStockScopesParts', [AdminController::class, 'createStockScopesParts'])->name('createStockScopesParts');
    Route::get('/createStockOtherPage', [AdminController::class, 'createStockOtherPage'])->name('createStockOtherPage');
    Route::post('/createStockOtherOperation', [AdminController::class, 'createStockOther'])->name('createStockOther');
    Route::get('/createStockDisposiblePage', [AdminController::class, 'createStockDisposiblePage'])->name('createStockDisposiblePage');
    Route::post('/createStockDisposible', [AdminController::class, 'createStockDisposible'])->name('createStockDisposible');
    Route::get('/createStockScopesPage/{id}', [AdminController::class, 'createStockScopesPage'])->name('createStockScopesPage');
    Route::post('/createStockScopes', [AdminController::class, 'createStockScopes'])->name('createStockScopes');
    Route::post('/searchOtherDatas', [AdminController::class, 'searchOtherDatas'])->name('searchOtherDatas');
    Route::get('/detailsProducts/{id}', [AdminController::class, 'detailsProducts'])->name('detailsProducts');
    Route::get('/editProducts/{id}', [AdminController::class, 'editProducts'])->name('editProducts');
    Route::any('/updateOperationStockScopes/{id}', [AdminController::class, 'updateOperationStockScopes'])->name('updateOperationStockScopes');
    Route::any('/updateOperationStockOther/{id}', [AdminController::class, 'updateOperationStockOther'])->name('updateOperationStockOther');
    Route::any('/updateOperationStockDisposible/{id}', [AdminController::class, 'updateOperationStockDisposible'])->name('updateOperationStockDisposible');
    Route::any('/updateOperationStockScopesParts/{id}', [AdminController::class, 'updateOperationStockScopesParts'])->name('updateOperationStockScopesParts');
    Route::get('/outgoingDataStock/{id}', [AdminController::class, 'outgoingDataStock'])->name('outgoingDataStock');
    Route::post('/outgoingDisposibleItem', [AdminController::class, 'outgoingDisposibleItem'])->name('outgoingDisposibleItem');
    Route::get('/outgoingDataStocks/{id}', [AdminController::class, 'outgoingDataStocks'])->name('outgoingDataStocks');
    Route::post('/outgoingPartsItem', [AdminController::class, 'outgoingPartsItem'])->name('outgoingPartsItem');
    Route::post('/searchOtherDatass', [AdminController::class, 'searchOtherDatass'])->name('searchOtherDatass');
    Route::get('/stockHistory/{id}', [AdminController::class, 'stockHistory'])->name('stockHistory');
    Route::any('/removeOperationStocksData/{id}', [AdminController::class, 'removeOperationStocksData'])->name('removeOperationStocksData');
    Route::get('/getStocksData', [AdminController::class, 'getStocksData'])->name('getStocksData');
    Route::get('/outgoingSystemDataStock/{id}', [AdminController::class, 'outgoingSystemDataStock'])->name('outgoingSystemDataStock');
    Route::post('/outgoingSystemItem', [AdminController::class, 'outgoingSystemItem'])->name('outgoingSystemItem');
    Route::get('/addNewAttendancePage', [AdminController::class, 'addNewAttendancePage'])->name('addNewAttendancePage');
    Route::post('/attendanceOperation', [AdminController::class, 'attendanceOperation'])->name('attendanceOperation');
    Route::get('/attendanceList', [AdminController::class, 'attendanceList'])->name('attendanceList');
    Route::get('/attendanceEditPage/{id}', [AdminController::class, 'attendanceEditPage'])->name('attendanceEditPage');
    Route::any('/attendanceUpdateOperation/{id}', [AdminController::class, 'attendanceUpdateOperation'])->name('attendanceUpdateOperation');
    Route::get('/attendanceDetailsPage/{id}', [AdminController::class, 'attendanceDetailsPage'])->name('attendanceDetailsPage');
    Route::get('/createExpensesCategoryPage', [AdminController::class, 'createExpensesCategoryPage'])->name('createExpensesCategoryPage');
    Route::post('/createExpensesCategoryOperation', [AdminController::class, 'createExpensesCategoryOperation'])->name('createExpensesCategoryOperation');
    Route::get('/createExpensesPage', [AdminController::class, 'createExpensesPage'])->name('createExpensesPage');
    Route::get('/categoryExpenses', [AdminController::class, 'categoryExpenses'])->name('categoryExpenses');
    Route::post('/createExpensesOperation', [AdminController::class, 'createExpensesOperation'])->name('createExpensesOperation');
    Route::get('/expenseCategoryListPage', [AdminController::class, 'expenseCategoryListPage'])->name('expenseCategoryListPage');
    Route::any('/removeExpensesCategoryPage/{id}', [AdminController::class, 'removeExpensesCategoryPage'])->name('removeExpensesCategoryPage');
    Route::get('/editExpensesCategoryPage/{id}', [AdminController::class, 'editExpensesCategoryPage'])->name('editExpensesCategoryPage');
    Route::any('/updateExpensesCategoryOperation/{id}', [AdminController::class, 'updateExpensesCategoryOperation'])->name('updateExpensesCategoryOperation');
    Route::get('detailExpensesPage', [AdminController::class, 'detailExpensesPage'])->name('detailExpensesPage');
    Route::get('/detailsExpensesByCategory/{id}', [AdminController::class, 'detailsExpensesByCategory'])->name('detailsExpensesByCategory');
    Route::get('/createExpensesBankPage', [AdminController::class, 'createExpensesBankPage'])->name('createExpensesBankPage');
    Route::post('/createExpensesBankOperation', [AdminController::class, 'createExpensesBankOperation'])->name('createExpensesBankOperation');
    Route::get('/detailExpensesBanksPage', [AdminController::class, 'detailExpensesBanksPage'])->name('detailExpensesBanksPage');
    Route::get('/createDataIncomingAndOutgoingDailyCreatingPage', [AdminController::class, 'createDataIncomingAndOutgoingDailyCreatingPage'])->name('createDataIncomingAndOutgoingDailyCreatingPage');
    Route::get('/createPageDisposibleIncomingAndOutgoingDaily', [AdminController::class, 'createPageDisposibleIncomingAndOutgoingDaily'])->name('createPageDisposibleIncomingAndOutgoingDaily');
    Route::get('/incomingAndOutgoingDailyRecordDataList', [AdminController::class, 'incomingAndOutgoingDailyRecordDataList'])->name('incomingAndOutgoingDailyRecordDataList');
    Route::get('/createAdminProfilePage', [AdminController::class, 'createAdminProfilePage'])->name('createAdminProfilePage');
    Route::post('/changerUserPassword', [AdminController::class, 'changerUserPassword'])->name('changerUserPassword');
    Route::post('/personalinformation', [AdminController::class, 'personalinformation'])->name('personalinformation');
    Route::put('/editPersonalInformation', [AdminController::class, 'editPersonalInformation'])->name('editPersonalInformation');
    Route::any('notificationReadStatus/{id}', [AdminController::class, 'notificationReadStatus'])->name('notificationReadStatus');
    Route::get('/createLeavePage', [AdminController::class, 'createLeavePage'])->name('createLeavePage');
    Route::post('/createOperationLeavePage', [AdminController::class, 'createOperationLeavePage'])->name('createOperationLeavePage');
    Route::get('/leaveListPage', [AdminController::class, 'leaveListPage'])->name('leaveListPage');
    Route::get('/leaveDetails/{id}', [AdminController::class, 'leaveDetails'])->name('leaveDetails');
    Route::any('/removeLeaveOperation/{id}', [AdminController::class, 'removeLeaveOperation'])->name('removeLeaveOperation');
    Route::any('/approveLeave/{id}', [AdminController::class, 'approveLeave'])->name('approveLeave');
    Route::any('rejectedLeave/{id}', [AdminController::class, 'rejectedLeave'])->name('rejectedLeave');
    Route::get('/allLeaveListPage', [AdminController::class, 'allLeaveListPage'])->name('allLeaveListPage');
    Route::any('/checkEmployeePresentOrAbsent', [AdminController::class, 'checkEmployeePresentOrAbsent'])->name('checkEmployeePresentOrAbsent');
    Route::any('/createNotificationQtvChecker', [AdminController::class, 'createNotificationQtvChecker'])->name('createNotificationQtvChecker');
    Route::any('/removeAttendanceDetails/{id}', [AdminController::class, 'removeAttendanceDetails'])->name('removeAttendanceDetails');
    Route::get('/clientPaymentReceivedPage/{id}', [AdminController::class, 'clientPaymentReceivedPage'])->name('clientPaymentReceivedPage');
    Route::post('/clientPaymentReceivedOperation', [AdminController::class, 'clientPaymentReceivedOperation'])->name('clientPaymentReceivedOperation');
    Route::get('/reportClientReportingSystem', [AdminController::class, 'reportClientReportingSystem'])->name('reportClientReportingSystem');
    Route::get('/reportMonthlyExpenseReportingSystem', [AdminController::class, 'reportMonthlyExpenseReportingSystem'])->name('reportMonthlyExpenseReportingSystem');
    Route::post('/getDataForMonthWiseExpenseReport', [AdminController::class, 'getDataForMonthWiseExpenseReport'])->name('getDataForMonthWiseExpenseReport');
    Route::get('/reportMonthBankStatementReportingSystem', [AdminController::class, 'reportMonthBankStatementReportingSystem'])->name('reportMonthBankStatementReportingSystem');
    Route::post('/getDataForMonthWiseBankReport', [AdminController::class, 'getDataForMonthWiseBankReport'])->name('getDataForMonthWiseBankReport');
    Route::post('/getDataForMonthAttendanceDetailsPage/{id}', [AdminController::class, 'getDataForMonthAttendanceDetailsPage'])->name('getDataForMonthAttendanceDetailsPage');
    Route::post('/getDataForMonthdetailExpensesPage', [AdminController::class, 'getDataForMonthdetailExpensesPage'])->name('getDataForMonthdetailExpensesPage');
    Route::post('/getDataForMonthdetailExpensesBanksPage', [AdminController::class, 'getDataForMonthdetailExpensesBanksPage'])->name('getDataForMonthdetailExpensesBanksPage');
    Route::get('/viewStockDetailsPage', [AdminController::class, 'viewStockDetailsPage'])->name('viewStockDetailsPage');
    Route::any('/deactiveUser/{id}', [AdminController::class, 'deactiveUser'])->name('deactiveUser');
    Route::any('/activeUser/{id}', [AdminController::class, 'activeUser'])->name('activeUser');
    Route::any('/updateOperationStatus', [AdminController::class, 'updateOperationStatus'])->name('updateOperationStatus');
});
// ====================================================== ! admin routes ======================================================
// ====================================================== employee routes =====================================================
Route::group(['middleware' => ['employee']], function () {
    Route::get('/employeeDashboardPage', [employeeController::class, 'employeeDashboardPage'])->name('employeeDashboardPage');
    Route::any('/logoutOperationz', [employeeController::class, 'logoutOperation'])->name('logoutOperation');
    Route::get('/listEmployees', [employeeController::class, 'employeeList'])->name('employeeList');
    Route::get('/searchEmployeesByemployees', [employeeController::class, 'searchEmployeesByemployees'])->name('searchEmployeesByemployees');
    Route::get('/newEmployeeCreatePage', [employeeController::class, 'newEmployeeCreatePage'])->name('newEmployeeCreatePage');
    Route::post('/newEmployeesCreateOperation', [employeeController::class, 'newEmployeesCreateOperation'])->name('newEmployeesCreateOperation');
    Route::get('/employeeDetailsPage/{id}', [employeeController::class, 'employeeDetailsPage'])->name('employeeDetailsPage');
    Route::get('/addNewEmployeesAttendancePage', [employeeController::class, 'addNewEmployeesAttendancePage'])->name('addNewEmployeesAttendancePage');
    Route::post('/attendanceEmployeesCreationOperation', [employeeController::class, 'attendanceEmployeesCreationOperation'])->name('attendanceEmployeesCreationOperation');
    Route::get('/attendanceEmployeesList', [employeeController::class, 'attendanceEmployeesList'])->name('attendanceEmployeesList');
    Route::get('/attendanceEmployeesEditPage/{id}', [employeeController::class, 'attendanceEmployeesEditPage'])->name('attendanceEmployeesEditPage');
    Route::any('/attendanceEmployeesUpdateOperation/{id}', [employeeController::class, 'attendanceEmployeesUpdateOperation'])->name('attendanceEmployeesUpdateOperation');
    Route::get('/attendanceEmployeesDetailsPage/{id}', [employeeController::class, 'attendanceEmployeesDetailsPage'])->name('attendanceEmployeesDetailsPage');
    Route::post('/searchAttendanceMonthWiseAndYear/{id}', [employeeController::class, 'searchAttendanceMonthWiseAndYear'])->name('searchAttendanceMonthWiseAndYear');
    Route::get('/holidayLeaveLists', [employeeController::class, 'holidayLeaveLists'])->name('holidayLeaveLists');
    Route::get('/newLeavePage', [employeeController::class, 'newLeavePage'])->name('newLeavePage');
    Route::post('/newLeaveCreationOperation', [employeeController::class, 'newLeaveCreationOperation'])->name('newLeaveCreationOperation');
    Route::get('/holidayLeaveDetails/{id}', [employeeController::class, 'holidayLeaveDetails'])->name('holidayLeaveDetails');
    Route::get('/stockDisposibleItemsList', [employeeController::class, 'stockDisposibleItemsList'])->name('stockDisposibleItemsList');
    Route::get('/otherItemsListIncludedParts', [employeeController::class, 'otherItemsListIncludedParts'])->name('otherItemsListIncludedParts');
    Route::get('/newStockDisposiblePage', [employeeController::class, 'newStockDisposiblePage'])->name('newStockDisposiblePage');
    Route::post('/newStockDisposibleCreateOperation', [employeeController::class, 'newStockDisposibleCreateOperation'])->name('newStockDisposibleCreateOperation');
    Route::get('/ProductDetailsData/{id}', [employeeController::class, 'ProductDetailsData'])->name('ProductDetailsData');
    Route::post('/searchDisposibleItems', [employeeController::class, 'searchDisposibleItems'])->name('searchDisposibleItems');
    Route::get('/productUseHistoryDetails/{id}', [employeeController::class, 'productUseHistoryDetails'])->name('productUseHistoryDetails');
    Route::get('/editProductsPage/{id}', [employeeController::class, 'editProductsPage'])->name('editProductsPage');
    Route::any('/updateOperationStockDisposibleData/{id}', [employeeController::class, 'updateOperationStockDisposibleData'])->name('updateOperationStockDisposibleData');
    Route::any('/updateOperationStockOtherData/{id}', [employeeController::class, 'updateOperationStockOtherData'])->name('updateOperationStockOtherData');
    Route::any('/updateOperationStockScopesData/{id}', [employeeController::class, 'updateOperationStockScopesData'])->name('updateOperationStockScopesData');
    Route::any('/updateOperationStockScopesPartsData/{id}', [employeeController::class, 'updateOperationStockScopesPartsData'])->name('updateOperationStockScopesPartsData');
    Route::post('/searchOtherItems', [employeeController::class, 'searchOtherItems'])->name('searchOtherItems');
    Route::any('/createNotificationsQtvCheckers', [employeeController::class, 'createNotificationsQtvCheckers'])->name('createNotificationsQtvCheckers');
    Route::get('/newStockScopesPartsPage', [employeeController::class, 'newStockScopesPartsPage'])->name('newStockScopesPartsPage');
    Route::get('/newStockOtherPage', [employeeController::class, 'newStockOtherPage'])->name('newStockOtherPage');
    Route::post('/newStockScopesPartsOperation', [employeeController::class, 'newStockScopesPartsOperation'])->name('newStockScopesPartsOperation');
    Route::post('/newStockOtherOperation', [employeeController::class, 'newStockOtherOperation'])->name('newStockOtherOperation');
    Route::get('/newOfficeExpensePage', [employeeController::class, 'newOfficeExpensePage'])->name('newOfficeExpensePage');
    Route::post('/newOfficeCreateExpenseOperation', [employeeController::class, 'newOfficeCreateExpenseOperation'])->name('newOfficeCreateExpenseOperation');
    Route::get('/detailsExpensesPagesss', [employeeController::class, 'detailsExpensesPagesss'])->name('detailsExpensesPagesss');
    Route::post('/filterSystemMonthWiseExpenseDetails', [employeeController::class, 'filterSystemMonthWiseExpenseDetails'])->name('filterSystemMonthWiseExpenseDetails');
    Route::get('/withoutTjfScopeInspectionIncomingListPage', [employeeController::class, 'withoutTjfScopeInspectionIncomingListPage'])->name('withoutTjfScopeInspectionIncomingListPage');
    Route::post('/searchOperationIncomingGastroAndColonoScopeReport', [employeeController::class, 'searchOperationIncomingGastroAndColonoScopeReport'])->name('searchOperationIncomingGastroAndColonoScopeReport');
    Route::get('/inspectionReportScopesDetails/{id}', [employeeController::class, 'inspectionReportScopesDetails'])->name('inspectionReportScopesDetails');
    Route::get('/outgoingScopeRepairingParts/{id}', [employeeController::class, 'outgoingScopeRepairingParts'])->name('outgoingScopeRepairingParts');
    Route::post('/outgoingScopeRepairingPartsOperation', [employeeController::class, 'outgoingScopeRepairingPartsOperation'])->name('outgoingScopeRepairingPartsOperation');
    Route::get('/newStockScopesPage/{id}', [employeeController::class, 'newStockScopesPage'])->name('newStockScopesPage');
    Route::post('/newStockScopesOperation', [employeeController::class, 'newStockScopesOperation'])->name('newStockScopesOperation');
    Route::get('/withoutTjfIncomingInspectionCreatingPage', [employeeController::class, 'withoutTjfIncomingInspectionCreatingPage'])->name('withoutTjfIncomingInspectionCreatingPage');
    Route::post('/withoutTjfIncomingInspectionCreatingOperation', [employeeController::class, 'withoutTjfIncomingInspectionCreatingOperation'])->name('withoutTjfIncomingInspectionCreatingOperation');
    Route::get('/TjfIncomingCreatingInspectionPage', [employeeController::class, 'TjfIncomingCreatingInspectionPage'])->name('TjfIncomingCreatingInspectionPage');
    Route::post('/TjfIncomingCreateInspectionOperation', [employeeController::class, 'TjfIncomingCreateInspectionOperation'])->name('TjfIncomingCreateInspectionOperation');
    Route::get('/dailyCreateIncomingAndOutGoingRecordPages/{id}', [employeeController::class, 'dailyCreateIncomingAndOutGoingRecordPages'])->name('dailyCreateIncomingAndOutGoingRecordPages');
    Route::post('/createNewOperationIncomingAndOutgoingDailyRecord', [employeeController::class, 'createNewOperationIncomingAndOutgoingDailyRecord'])->name('createNewOperationIncomingAndOutgoingDailyRecord');
    Route::get('/listIncomingAndOutGoingDailyRecord', [employeeController::class, 'listIncomingAndOutGoingDailyRecord'])->name('listIncomingAndOutGoingDailyRecord');
    Route::get('/withoutTjfOutgoingInspectionCreatingPage/{id}', [employeeController::class, 'withoutTjfOutgoingInspectionCreatingPage'])->name('withoutTjfOutgoingInspectionCreatingPage');
    Route::post('/withoutTjfOutgoingInspectionCreatingOperation', [employeeController::class, 'withoutTjfOutgoingInspectionCreatingOperation'])->name('withoutTjfOutgoingInspectionCreatingOperation');
    Route::post('/TjfOutgoingInspectionCreatingOperation', [employeeController::class, 'TjfOutgoingInspectionCreatingOperation'])->name('TjfOutgoingInspectionCreatingOperation');
    Route::get('/editIncomingAndOutGoingDailyRecordPage/{id}', [employeeController::class, 'editIncomingAndOutGoingDailyRecordPage'])->name('editIncomingAndOutGoingDailyRecordPage');
    Route::any('/dailyRecordEditOperationIncomingAndOutgoing/{id}', [employeeController::class, 'dailyRecordEditOperationIncomingAndOutgoing'])->name('dailyRecordEditOperationIncomingAndOutgoing');
    Route::post('/filterSystemAccordingIncomingAndOutgoing', [employeeController::class, 'filterSystemAccordingIncomingAndOutgoing'])->name('filterSystemAccordingIncomingAndOutgoing');
    Route::get('/withoutTjfScopesInspectionOutgoingListPage', [employeeController::class, 'withoutTjfScopesInspectionOutgoingListPage'])->name('withoutTjfScopesInspectionOutgoingListPage');
    Route::get('/searchOperationOutgoingGastroAndColonoScopeReport', [employeeController::class, 'searchOperationOutgoingGastroAndColonoScopeReport'])->name('searchOperationOutgoingGastroAndColonoScopeReport');
    Route::get('/detailsOperationPageOutgoingGastroAndColonoScope/{id}', [employeeController::class, 'detailsOperationPageOutgoingGastroAndColonoScope'])->name('detailsOperationPageOutgoingGastroAndColonoScope');
    Route::get('/othersIncomingAndOutgoingDataDailyRecordList', [employeeController::class, 'othersIncomingAndOutgoingDataDailyRecordList'])->name('othersIncomingAndOutgoingDataDailyRecordList');
    Route::post('/searchOperationOthersIncomingAndOutgoingDataDailyRecord', [employeeController::class, 'searchOperationOthersIncomingAndOutgoingDataDailyRecord'])->name('searchOperationOthersIncomingAndOutgoingDataDailyRecord');
    Route::get('/newCreateDataIncomingAndOutgoingDailyCreatingPage', [employeeController::class, 'newCreateDataIncomingAndOutgoingDailyCreatingPage'])->name('newCreateDataIncomingAndOutgoingDailyCreatingPage');
    Route::get('/newCreatePageDisposibleIncomingAndOutgoingDaily', [employeeController::class, 'newCreatePageDisposibleIncomingAndOutgoingDaily'])->name('newCreatePageDisposibleIncomingAndOutgoingDaily');
    Route::post('/newCreateOperationIncomingAndOutgoingDisposibleDailyRecord', [employeeController::class, 'newCreateOperationIncomingAndOutgoingDisposibleDailyRecord'])->name('newCreateOperationIncomingAndOutgoingDisposibleDailyRecord');
    Route::post('/newCreateOperationIncomingAndOutgoingDataDailyRecord', [employeeController::class, 'newCreateOperationIncomingAndOutgoingDataDailyRecord'])->name('newCreateOperationIncomingAndOutgoingDataDailyRecord');
    Route::post('/searchOperationDataIncomingAndOutgoingDataDailyRecord', [employeeController::class, 'searchOperationDataIncomingAndOutgoingDataDailyRecord'])->name('searchOperationDataIncomingAndOutgoingDataDailyRecord');
    Route::get('/pageEditIncomingAndOutgoingDataDailyRecordPage/{id}', [employeeController::class, 'pageEditIncomingAndOutgoingDataDailyRecordPage'])->name('pageEditIncomingAndOutgoingDataDailyRecordPage');
    Route::any('/pageUpdateOperationIncomingAndOutgoingDisposibleDailyRecord/{id}', [employeeController::class, 'pageUpdateOperationIncomingAndOutgoingDisposibleDailyRecord'])->name('pageUpdateOperationIncomingAndOutgoingDisposibleDailyRecord');
    Route::any('/pageUpdateOperationIncomingAndOutgoingDataDailyRecord/{id}', [employeeController::class, 'pageUpdateOperationIncomingAndOutgoingDataDailyRecord'])->name('pageUpdateOperationIncomingAndOutgoingDataDailyRecord');
    Route::get('/pageDetailIncomingAndOutgoingDataDailyRecordPage/{id}', [employeeController::class, 'pageDetailIncomingAndOutgoingDataDailyRecordPage'])->name('pageDetailIncomingAndOutgoingDataDailyRecordPage');
    Route::get('/pageServiceReportListPage', [employeeController::class, 'pageServiceReportListPage'])->name('pageServiceReportListPage');
    Route::post('/searchOperationServiceReport', [employeeController::class, 'searchOperationServiceReport'])->name('searchOperationServiceReport');
    Route::get('/pageCreateServiceReportPage', [employeeController::class, 'pageCreateServiceReportPage'])->name('pageCreateServiceReportPage');
    Route::post('/createOperationServiceReport', [employeeController::class, 'createOperationServiceReport'])->name('createOperationServiceReport');
    Route::get('/pageDetailServiceReportPage/{id}', [employeeController::class, 'pageDetailServiceReportPage'])->name('pageDetailServiceReportPage');
    Route::get('/pageQuotationListPage', [employeeController::class, 'pageQuotationListPage'])->name('pageQuotationListPage');
    Route::get('/pageQuotationListWithOutLogoPage', [employeeController::class, 'pageQuotationListWithOutLogoPage'])->name('pageQuotationListWithOutLogoPage');
    Route::post('/searchOperationQuotations', [employeeController::class, 'searchOperationQuotations'])->name('searchOperationQuotations');
    Route::get('/pageCreateRepairingQuotationPage', [employeeController::class, 'pageCreateRepairingQuotationPage'])->name('pageCreateRepairingQuotationPage');
    Route::post('/createOperationQuotationRepairingOperation', [employeeController::class, 'createOperationQuotationRepairingOperation'])->name('createOperationQuotationRepairingOperation');
    Route::get('/pageCreateDisposibleQuotationPage', [employeeController::class, 'pageCreateDisposibleQuotationPage'])->name('pageCreateDisposibleQuotationPage');
    Route::post('/createOperationQuotationDisposibleOperation', [employeeController::class, 'createOperationQuotationDisposibleOperation'])->name('createOperationQuotationDisposibleOperation');
    Route::get('/pageCreateRepairingDataSS', [employeeController::class, 'pageCreateRepairingDataSS'])->name('pageCreateRepairingDataSS');
    Route::post('/createOperationQuotationRepairing_Operations', [employeeController::class, 'createOperationQuotationRepairing_Operations'])->name('createOperationQuotationRepairing_Operations');
    Route::get('/getStockDataz', [employeeController::class, 'getStockDataz'])->name('getStockDataz');
    Route::get('/getStocksDataz', [employeeController::class, 'getStocksDataz'])->name('getStocksDataz');
    Route::get('/pageDetailQuotationPage/{id}', [employeeController::class, 'pageDetailQuotationPage'])->name('pageDetailQuotationPage');
    Route::get('/pageCreateInvoicePage/{id}', [employeeController::class, 'pageCreateInvoicePage'])->name('pageCreateInvoicePage');
    Route::post('/createOperationInvoiceRepairingOperation', [employeeController::class, 'createOperationInvoiceRepairingOperation'])->name('createOperationInvoiceRepairingOperation');
    Route::post('/createOperationInvoiceRepairingOperations', [employeeController::class, 'createOperationInvoiceRepairingOperations'])->name('createOperationInvoiceRepairingOperations');
    Route::post('/createOperationInvoiceRepairing_Operations', [employeeController::class, 'createOperationInvoiceRepairing_Operations'])->name('createOperationInvoiceRepairing_Operations');
    Route::post('/createOperationInvoiceRepairing_Operation', [employeeController::class, 'createOperationInvoiceRepairing_Operation'])->name('createOperationInvoiceRepairing_Operation');
    Route::post('/createOperationInvoiceDisposibleOperation', [employeeController::class, 'createOperationInvoiceDisposibleOperation'])->name('createOperationInvoiceDisposibleOperation');
    Route::post('/createOperationInvoiceDisposibleOperations', [employeeController::class, 'createOperationInvoiceDisposibleOperations'])->name('createOperationInvoiceDisposibleOperations');
    Route::post('/searchOperationQuotationss', [employeeController::class, 'searchOperationQuotationss'])->name('searchOperationQuotationss');
    Route::get('/pageDetailWithOutLogoQuotationPage/{id}', [employeeController::class, 'pageDetailWithOutLogoQuotationPage'])->name('pageDetailWithOutLogoQuotationPage');
    Route::get('/pageInvoiceListPage', [employeeController::class, 'pageInvoiceListPage'])->name('pageInvoiceListPage');
    Route::get('/pageCreateRepairingInvoicePage', [employeeController::class, 'pageCreateRepairingInvoicePage'])->name('pageCreateRepairingInvoicePage');
    Route::get('/pageCreateDisposibleInvoicePage', [employeeController::class, 'pageCreateDisposibleInvoicePage'])->name('pageCreateDisposibleInvoicePage');
    Route::get('/pageCreateRepairingDataSSInvoice', [employeeController::class, 'pageCreateRepairingDataSSInvoice'])->name('pageCreateRepairingDataSSInvoice');
    Route::post('/searchOperationInvoicesData', [employeeController::class, 'searchOperationInvoices'])->name('searchOperationInvoices');
    Route::post('/searchOperationInvoicessData', [employeeController::class, 'searchOperationInvoicess'])->name('searchOperationInvoicess');
    Route::get('/pageDetailInvoicePage/{id}', [employeeController::class, 'pageDetailInvoicePage'])->name('pageDetailInvoicePage');
    Route::get('/pageDetailWithOutLogoInvoicePage/{id}', [employeeController::class, 'pageDetailWithOutLogoInvoicePage'])->name('pageDetailWithOutLogoInvoicePage');
    Route::get('/pageCreateDeliveryChallanPage/{id}', [employeeController::class, 'pageCreateDeliveryChallanPage'])->name('pageCreateDeliveryChallanPage');
    Route::post('/createOperationDeliveryChallanOperation', [employeeController::class, 'createOperationDeliveryChallanOperation'])->name('createOperationDeliveryChallanOperation');
    Route::post('/createOperationDeliveryChallanOperations', [employeeController::class, 'createOperationDeliveryChallanOperations'])->name('createOperationDeliveryChallanOperations');
    Route::get('/pageDeliveryChallanListPage', [employeeController::class, 'pageDeliveryChallanListPage'])->name('pageDeliveryChallanListPage');
    Route::get('/pageDetailDeleiveryChallanPage/{id}', [employeeController::class, 'pageDetailDeleiveryChallanPage'])->name('pageDetailDeleiveryChallanPage');
    Route::post('/searchOperationDeliveryChallan', [employeeController::class, 'searchOperationDeliveryChallan'])->name('searchOperationDeliveryChallan');
    Route::get('/pageCreateClientAccountHistoryPage/{id}', [employeeController::class, 'pageCreateClientAccountHistoryPage'])->name('pageCreateClientAccountHistoryPage');
    Route::post('/createOperationAccountHistoryRepairing_Operation', [employeeController::class, 'createOperationAccountHistoryRepairing_Operation'])->name('createOperationAccountHistoryRepairing_Operation');
    Route::post('/createOperationAccountHistorySystemOperation', [employeeController::class, 'createOperationAccountHistorySystemOperation'])->name('createOperationAccountHistorySystemOperation');
    Route::post('/createOperationAccountHistoryDisposibleOperations', [employeeController::class, 'createOperationAccountHistoryDisposibleOperations'])->name('createOperationAccountHistoryDisposibleOperations');
    Route::get('/pageOutgoingDataStock/{id}', [employeeController::class, 'pageOutgoingDataStock'])->name('pageOutgoingDataStock');
    Route::post('/outgoingOperationDisposibleItem', [employeeController::class, 'outgoingOperationDisposibleItem'])->name('outgoingOperationDisposibleItem');
    Route::get('/pageInvoiceListWithOutLogoPage', [employeeController::class, 'pageInvoiceListWithOutLogoPage'])->name('pageInvoiceListWithOutLogoPage');
    Route::get('/pageDetailWithOutLogoInvoicePage/{id}', [employeeController::class, 'pageDetailWithOutLogoInvoicePage'])->name('pageDetailWithOutLogoInvoicePage');
    Route::post('/searchOperationInvoicess', [employeeController::class, 'searchOperationInvoicess'])->name('searchOperationInvoicess');
    Route::get('/pageOutgoingSystemDataStock/{id}', [employeeController::class, 'pageOutgoingSystemDataStock'])->name('pageOutgoingSystemDataStock');
    Route::post('/outgoingOperationSystemItem', [employeeController::class, 'outgoingOperationSystemItem'])->name('outgoingOperationSystemItem');
    Route::get('/pageCreateAdminProfilePage', [employeeController::class, 'pageCreateAdminProfilePage'])->name('pageCreateAdminProfilePage');
    Route::post('/personalinformationAddOperation', [employeeController::class, 'personalinformationAddOperation'])->name('personalinformationAddOperation');
    Route::post('/changerOperationUserPassword', [employeeController::class, 'changerOperationUserPassword'])->name('changerOperationUserPassword');
    Route::put('/editOperationPersonalInformation', [employeeController::class, 'editOperationPersonalInformation'])->name('editOperationPersonalInformation');
    Route::post('/createEmployeeSocialAccount', [employeeController::class, 'createEmployeeSocialAccount'])->name('createEmployeeSocialAccount');
    Route::post('/createEducationRecordFunction', [employeeController::class, 'createEducationRecordFunction'])->name('createEducationRecordFunction');
    Route::post('/createAdditionalEducationRecordFunction', [employeeController::class, 'createAdditionalEducationRecordFunction'])->name('createAdditionalEducationRecordFunction');
    Route::any('/editEmployeeSocialAccount/{id}', [employeeController::class, 'editEmployeeSocialAccount'])->name('editEmployeeSocialAccount');
    Route::any('/removeOperationSocialMedia/{id}', [employeeController::class, 'removeOperationSocialMedia'])->name('removeOperationSocialMedia');
    Route::any('/editEducationRecordFunction/{id}', [employeeController::class, 'editEducationRecordFunction'])->name('editEducationRecordFunction');
    Route::any('/removeOperationEducation/{id}', [employeeController::class, 'removeOperationEducation'])->name('removeOperationEducation');
    Route::any('/editAdditionalEducationRecordFunction/{id}', [employeeController::class, 'editAdditionalEducationRecordFunction'])->name('editAdditionalEducationRecordFunction');
    Route::any('/removeOperationAdditionalEducation/{id}', [employeeController::class, 'removeOperationAdditionalEducation'])->name('removeOperationAdditionalEducation');
});
// ====================================================== ! employee routes ====================================================
require __DIR__ . '/auth.php';
